version: 2
updates:
- package-ecosystem: composer
  directory: "/core/components/commerce_pdfcrowdwriter"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pdfcrowd/pdfcrowd
    versions:
    - 4.12.0
    - 5.0.0
